#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_PREFIX="aws-route-landing"
# shellcheck source=route-local-common.sh
source "$SCRIPT_DIR/route-local-common.sh"

STATE_FILE="${STATE_FILE:-$STATE_ROOT/landing.env}"
CONFIG_DIR="${CONFIG_DIR:-/etc/sing-box}"
CONFIG_FILE="${CONFIG_FILE:-$CONFIG_DIR/config.json}"
CREDENTIALS_FILE="${CREDENTIALS_FILE:-/root/aws-route-ss-credentials.env}"
NODE_FILE="${NODE_FILE:-/root/aws-route-ss-node.txt}"
UNIT_FILE="${UNIT_FILE:-/etc/systemd/system/sing-box.service}"

ACTION="install"
for argument in "$@"; do
  case "$argument" in
    install|status|generate-node|show-credentials|remove|help) ACTION="$argument" ;;
    -h|--help) ACTION=help ;;
    --yes|-y) AUTO_APPROVE=1 ;;
    --non-interactive) INTERACTIVE=0 ;;
    *) die "unknown option: $argument" ;;
  esac
done

LISTEN_PORT="${LISTEN_PORT:-8388}"
SS_METHOD="${SS_METHOD:-aes-128-gcm}"
NODE_ADDRESS="${NODE_ADDRESS:-}"
NODE_PORT="${NODE_PORT:-}"
NODE_NAME="${NODE_NAME:-Lagos-SS}"
SING_BOX_BIN="${SING_BOX_BIN:-}"
SING_BOX_VERSION="${SING_BOX_VERSION:-}"
SS_PASSWORD="${SS_PASSWORD:-}"

load_state() {
  [ -f "$STATE_FILE" ] || return 0
  require_private_file "$STATE_FILE"
  # The file is generated by this script and contains only validated values.
  # shellcheck disable=SC1090
  . "$STATE_FILE"
}

load_existing_credentials() {
  [ -f "$CREDENTIALS_FILE" ] || return 0
  require_private_file "$CREDENTIALS_FILE"
  # shellcheck disable=SC1090
  . "$CREDENTIALS_FILE"
  if [ -n "${SS_PASSWORD:-}" ]; then
    EXISTING_PASSWORD="$SS_PASSWORD"
  fi
  EXISTING_CREDENTIAL_PORT="${SS_PORT:-}"
  EXISTING_CREDENTIAL_METHOD="${SS_METHOD:-}"
}

require_landing_commands() {
  require_root
  require_command bash
  require_command ip
  require_command systemctl
  require_command awk
  require_command grep
}

find_sing_box_binary() {
  if [ -n "$SING_BOX_BIN" ] && [ -x "$SING_BOX_BIN" ]; then
    return 0
  fi
  for candidate in /usr/bin/sing-box /usr/local/bin/sing-box; do
    if [ -x "$candidate" ]; then
      SING_BOX_BIN="$candidate"
      return 0
    fi
  done
  return 1
}

existing_config_value() {
  local query="$1"
  if [ -f "$CONFIG_FILE" ] && command -v jq >/dev/null 2>&1; then
    require_private_file "$CONFIG_FILE"
    jq -r "$query" "$CONFIG_FILE" 2>/dev/null | head -n 1
  fi
}

choose_password() {
  local choice manual generated
  EXISTING_PASSWORD="${EXISTING_PASSWORD:-}"
  if [ -z "$EXISTING_PASSWORD" ]; then
    if ! is_interactive; then
      SS_PASSWORD="$(generate_hex_password)"
      return 0
    fi
    printf '\nPassword source:\n' >&2
    printf '  1. Generate a new password\n' >&2
    printf '  2. Enter a password manually\n' >&2
    printf 'Select [1]: ' >&2
    IFS= read -r choice || true
  else
    if ! is_interactive; then
      SS_PASSWORD="$EXISTING_PASSWORD"
      return 0
    fi
    printf '\nPassword source:\n' >&2
    printf '  1. Reuse the existing password\n' >&2
    printf '  2. Generate a new password\n' >&2
    printf '  3. Enter a password manually\n' >&2
    printf 'Select [1]: ' >&2
    IFS= read -r choice || true
  fi

  case "${choice:-1}" in
    1)
      if [ -n "$EXISTING_PASSWORD" ]; then
        SS_PASSWORD="$EXISTING_PASSWORD"
      else
        SS_PASSWORD="$(generate_hex_password)"
      fi
      ;;
    2)
      if [ -z "$EXISTING_PASSWORD" ]; then
        manual="$(prompt_secret "SS password")"
        SS_PASSWORD="$manual"
      else
        SS_PASSWORD="$(generate_hex_password)"
      fi
      ;;
    3)
      [ -n "$EXISTING_PASSWORD" ] || die "invalid password choice"
      manual="$(prompt_secret "SS password")"
      SS_PASSWORD="$manual"
      ;;
    *) die "invalid password choice" ;;
  esac
}

resolve_inputs() {
  local existing_port existing_method existing_node_port

  existing_port="$(existing_config_value '.inbounds[]? | select(.type == "shadowsocks") | .listen_port')"
  existing_method="$(existing_config_value '.inbounds[]? | select(.type == "shadowsocks") | .method')"
  existing_node_port="${NODE_PORT:-}"

  [ -n "$existing_port" ] && LISTEN_PORT="$existing_port"
  [ -n "${EXISTING_CREDENTIAL_PORT:-}" ] && LISTEN_PORT="$EXISTING_CREDENTIAL_PORT"
  LISTEN_PORT="$(prompt_with_default "Landing listen port" "$LISTEN_PORT")"
  validate_port_value "$LISTEN_PORT" || die "invalid landing listen port: $LISTEN_PORT"
  [ "$LISTEN_PORT" -ne 22 ] || die "refusing to use SSH port 22 as the SS port"

  [ -n "$existing_method" ] && SS_METHOD="$existing_method"
  [ -n "${EXISTING_CREDENTIAL_METHOD:-}" ] && SS_METHOD="$EXISTING_CREDENTIAL_METHOD"
  SS_METHOD="$(prompt_with_default "Shadowsocks method (fixed)" "$SS_METHOD")"
  [ "$SS_METHOD" = "aes-128-gcm" ] || die "this deployment script only permits aes-128-gcm"

  choose_password
  validate_password_value "$SS_PASSWORD" || die "password must be 24-128 characters using only letters, numbers, dot, underscore, or hyphen"

  if [ -z "$NODE_ADDRESS" ]; then
    if is_interactive; then
      printf 'Transit public IP or domain (blank to generate later): ' >&2
      IFS= read -r NODE_ADDRESS || true
    fi
  else
    NODE_ADDRESS="$(prompt_with_default "Transit public IP or domain" "$NODE_ADDRESS")"
  fi
  if [ -n "$NODE_ADDRESS" ]; then
    validate_node_address "$NODE_ADDRESS" || die "invalid transit public IP or domain: $NODE_ADDRESS"
  fi

  if [ -z "$NODE_PORT" ]; then
    NODE_PORT="${existing_node_port:-$LISTEN_PORT}"
  fi
  NODE_PORT="$(prompt_with_default "Transit public port" "$NODE_PORT")"
  validate_port_value "$NODE_PORT" || die "invalid transit public port: $NODE_PORT"

  NODE_NAME="$(prompt_with_default "Node name" "$NODE_NAME")"
  NODE_NAME="$(safe_fragment "$NODE_NAME")"
  [ -n "$NODE_NAME" ] || die "node name must contain at least one ASCII letter or number"
}

fetch_latest_release() {
  local releases tag version arch candidates candidate url digest
  local checksum_name checksum_url checksum_file

  require_command curl
  require_command jq
  require_command sha256sum
  arch="$(dpkg --print-architecture 2>/dev/null || true)"
  case "$arch" in
    amd64) candidates="sing-box_VERSION_linux_amd64.deb sing-box_VERSION_linux_x86_64.deb" ;;
    arm64) candidates="sing-box_VERSION_linux_aarch64.deb sing-box_VERSION_linux_arm64.deb" ;;
    *) die "unsupported Debian architecture: ${arch:-unknown}; supported: amd64, arm64" ;;
  esac

  releases="$(curl -4fsSL --proto '=https' --tlsv1.2 --retry 3 --max-time 30 'https://api.github.com/repos/SagerNet/sing-box/releases?per_page=100')"
  tag="$(printf '%s' "$releases" | jq -r '[.[] | select(.draft == false and .prerelease == false)][0].tag_name // empty')"
  [ -n "$tag" ] || die "could not find the latest stable sing-box release"
  case "$tag" in
    v[0-9]*.[0-9]*.[0-9]*) ;;
    *) die "unexpected sing-box release tag: $tag" ;;
  esac
  version="${tag#v}"
  SING_BOX_VERSION="$tag"

  for candidate in $candidates; do
    candidate="${candidate//VERSION/$version}"
    url="$(printf '%s' "$releases" | jq -r --arg name "$candidate" '.[].assets[] | select(.name == $name) | .browser_download_url' | head -n 1)"
    if [ -n "$url" ]; then
      SING_BOX_ASSET_NAME="$candidate"
      SING_BOX_ASSET_URL="$url"
      digest="$(printf '%s' "$releases" | jq -r --arg name "$candidate" '.[].assets[] | select(.name == $name) | (.digest // empty)' | head -n 1)"
      SING_BOX_ASSET_DIGEST="${digest#sha256:}"
      break
    fi
  done
  [ -n "${SING_BOX_ASSET_URL:-}" ] || die "latest stable release has no supported Debian package for $arch"
  if [ -z "${SING_BOX_ASSET_DIGEST:-}" ]; then
    checksum_name="$(printf '%s' "$releases" | jq -r '[.[].assets[] | select(.name|test("sha256|checksums"; "i")) | select(.name|test("(txt|sha256)$"; "i")) | .name][0] // empty')"
    if [ -n "$checksum_name" ]; then
      checksum_url="$(printf '%s' "$releases" | jq -r --arg name "$checksum_name" '.[].assets[] | select(.name == $name) | .browser_download_url' | head -n 1)"
      checksum_file="$(mktemp /tmp/sing-box-checksum.XXXXXX)"
      curl -4fsSL --proto '=https' --tlsv1.2 --retry 3 --max-time 60 "$checksum_url" -o "$checksum_file"
      SING_BOX_ASSET_DIGEST="$(grep -i -F "$SING_BOX_ASSET_NAME" "$checksum_file" | grep -Eo '[0-9a-fA-F]{64}' | head -n 1 | tr '[:upper:]' '[:lower:]' || true)"
      unlink "$checksum_file"
    fi
  fi
  [ -n "${SING_BOX_ASSET_DIGEST:-}" ] || die "latest stable release did not expose a SHA256 digest for $SING_BOX_ASSET_NAME"
}

render_config() {
  jq -n \
    --arg password "$SS_PASSWORD" \
    --argjson port "$LISTEN_PORT" \
    '{
      log: {level: "info", timestamp: true},
      inbounds: [{
        type: "shadowsocks",
        tag: "chain-ss-in",
        listen: "0.0.0.0",
        listen_port: $port,
        method: "aes-128-gcm",
        password: $password,
        multiplex: {enabled: false}
      }],
      outbounds: [{type: "direct", tag: "direct"}],
      route: {auto_detect_interface: true}
    }'
}

render_state() {
  cat <<EOF
LISTEN_PORT=$LISTEN_PORT
SS_METHOD=$SS_METHOD
NODE_ADDRESS=$NODE_ADDRESS
NODE_PORT=$NODE_PORT
NODE_NAME=$NODE_NAME
SING_BOX_BIN=$SING_BOX_BIN
SING_BOX_VERSION=$SING_BOX_VERSION
EOF
}

build_node_outputs() {
  local encoded host fragment
  SS_URI=""
  SURGE_LINE=""
  [ -n "$NODE_ADDRESS" ] || return 0
  encoded="$(base64url_encode "$SS_METHOD:$SS_PASSWORD")"
  host="$(format_endpoint "$NODE_ADDRESS")"
  fragment="$(safe_fragment "$NODE_NAME")"
  SS_URI="ss://$encoded@$host:$NODE_PORT#$fragment"
  SURGE_LINE="$NODE_NAME = ss, $host, $NODE_PORT, encrypt-method=$SS_METHOD, password=$SS_PASSWORD, udp-relay=true"
}

render_credentials() {
  cat <<EOF
SS_PORT=$LISTEN_PORT
SS_METHOD=$SS_METHOD
SS_PASSWORD=$SS_PASSWORD
EOF
}

render_node_file() {
  build_node_outputs
  [ -n "$SS_URI" ] || return 0
  printf '%s\n%s\n' "$SS_URI" "$SURGE_LINE"
}

render_unit() {
  cat <<EOF
[Unit]
Description=sing-box Shadowsocks landing service
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$SING_BOX_BIN run -c $CONFIG_FILE
Restart=on-failure
RestartSec=5s
NoNewPrivileges=true
PrivateTmp=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=$CONFIG_DIR

[Install]
WantedBy=multi-user.target
EOF
}

LANDING_MUTATION_STARTED=0
LANDING_WAS_ACTIVE=0
LANDING_WAS_ENABLED=0
rollback_landing() {
  set +e
  systemctl disable --now sing-box.service >/dev/null 2>&1 || true
  restore_file "$CONFIG_FILE"
  restore_file "$STATE_FILE"
  restore_file "$CREDENTIALS_FILE"
  restore_file "$NODE_FILE"
  restore_file "$UNIT_FILE"
  systemctl daemon-reload >/dev/null 2>&1 || true
  if [ "$LANDING_WAS_ENABLED" -eq 1 ]; then
    systemctl enable sing-box.service >/dev/null 2>&1 || true
  fi
  if [ "$LANDING_WAS_ACTIVE" -eq 1 ]; then
    systemctl start sing-box.service >/dev/null 2>&1 || true
  fi
  set -e
}

on_landing_error() {
  local rc="$?"
  if [ "$LANDING_MUTATION_STARTED" -eq 1 ]; then
    warn "deployment failed; restoring the previous managed files"
    rollback_landing
  fi
  exit "$rc"
}

verify_landing() {
  local egress_ip

  find_sing_box_binary || die "sing-box binary is missing"
  "$SING_BOX_BIN" check -c "$CONFIG_FILE" >/dev/null
  systemctl is-active --quiet sing-box.service || die "sing-box.service is not active"
  systemctl is-enabled --quiet sing-box.service || die "sing-box.service is not enabled"
  ss -lnt | grep -q "0.0.0.0:$LISTEN_PORT" || die "sing-box TCP listener is not present"
  ss -lun | grep -q "0.0.0.0:$LISTEN_PORT" || die "sing-box UDP listener is not present"
  egress_ip="$(get_public_ipv4 2>/dev/null || true)"

  build_node_outputs
  printf '\nLanding Shadowsocks is configured\n'
  print_result "DEPLOYMENT_STATUS" "READY"
  print_result "ROLE" "LANDING"
  print_result "SING_BOX_VERSION" "$SING_BOX_VERSION"
  print_result "SING_BOX_STATUS" "active"
  print_result "LISTEN_ADDRESS" "0.0.0.0"
  print_result "LISTEN_PORT" "$LISTEN_PORT"
  print_result "METHOD" "$SS_METHOD"
  print_result "NETWORK" "TCP+UDP"
  print_result "UOT" "off"
  print_result "MULTIPLEX" "off"
  print_result "CONFIG_MODE" "600 root:root"
  print_result "LANDING_EGRESS_IP" "${egress_ip:-UNAVAILABLE}"
  if [ -n "$SS_URI" ]; then
    printf '\nGeneric SS node:\n%s\n' "$SS_URI"
    printf '\nSurge policy:\n%s\n' "$SURGE_LINE"
    print_result "NODE_FILE" "$NODE_FILE"
  else
    print_result "NODE_STATUS" "PENDING_PUBLIC_ENDPOINT"
  fi
  print_result "CREDENTIALS_FILE" "$CREDENTIALS_FILE"
  print_result "BACKUP_PATH" "$BACKUP_PATH"
}

install_landing() {
  local temporary_config package digest

  load_state
  load_existing_credentials
  require_supported_debian
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq
  apt-get install -y -qq ca-certificates curl jq openssl dpkg >/dev/null
  fetch_latest_release
  find_sing_box_binary || true
  resolve_inputs
  build_node_outputs

  printf '\nDeployment plan:\n'
  detail "Role: landing EC2"
  detail "sing-box: latest stable ($SING_BOX_VERSION)"
  detail "Listen: 0.0.0.0:$LISTEN_PORT TCP+UDP"
  detail "Method: $SS_METHOD"
  detail "UoT: off; Multiplex: off"
  detail "Public node endpoint: ${NODE_ADDRESS:-not set; generate later}"
  confirm_action "Apply this plan?" no || die "operation cancelled"

  start_backup landing
  backup_file "$CONFIG_FILE"
  backup_file "$STATE_FILE"
  backup_file "$CREDENTIALS_FILE"
  backup_file "$NODE_FILE"
  backup_file "$UNIT_FILE"
  if systemctl is-active --quiet sing-box.service; then
    LANDING_WAS_ACTIVE=1
  fi
  if systemctl is-enabled --quiet sing-box.service; then
    LANDING_WAS_ENABLED=1
  fi
  LANDING_MUTATION_STARTED=1
  trap on_landing_error ERR

  package="$(mktemp /tmp/sing-box.XXXXXX.deb)"
  curl -4fsSL --proto '=https' --tlsv1.2 --retry 3 --max-time 180 "$SING_BOX_ASSET_URL" -o "$package"
  digest="$(sha256sum "$package" | awk '{print $1}')"
  [ "$digest" = "$SING_BOX_ASSET_DIGEST" ] || die "sing-box package SHA256 mismatch"
  apt-get install -y -qq "$package" >/dev/null
  unlink "$package"
  find_sing_box_binary || die "sing-box package installed without a usable binary"

  temporary_config="$(mktemp)"
  render_config >"$temporary_config"
  "$SING_BOX_BIN" check -c "$temporary_config" >/dev/null
  unlink "$temporary_config"

  systemctl stop sing-box.service >/dev/null 2>&1 || true
  write_root_file "$(render_config)" "$CONFIG_FILE" 600
  write_root_file "$(render_state)" "$STATE_FILE" 600
  write_root_file "$(render_credentials)" "$CREDENTIALS_FILE" 600
  if [ -n "$SS_URI" ]; then
    write_root_file "$(render_node_file)" "$NODE_FILE" 600
  fi
  write_root_file "$(render_unit)" "$UNIT_FILE" 644
  systemctl daemon-reload
  systemctl enable --now sing-box.service >/dev/null
  sleep 2
  verify_landing
  trap - ERR
}

status_landing() {
  local password method port version egress
  require_root
  require_command systemctl
  require_command ss
  load_state
  if [ ! -f "$CONFIG_FILE" ]; then
    print_result "DEPLOYMENT_STATUS" "NOT_CONFIGURED"
    return 0
  fi
  password="$(existing_config_value '.inbounds[]? | select(.type == "shadowsocks") | .password')"
  method="$(existing_config_value '.inbounds[]? | select(.type == "shadowsocks") | .method')"
  port="$(existing_config_value '.inbounds[]? | select(.type == "shadowsocks") | .listen_port')"
  version="$(find_sing_box_binary && "$SING_BOX_BIN" version 2>/dev/null | awk 'NR == 1 {print $3}' || true)"
  egress="$(get_public_ipv4 2>/dev/null || true)"
  print_result "ROLE" "LANDING"
  print_result "SING_BOX_VERSION" "${version:-${SING_BOX_VERSION:-UNAVAILABLE}}"
  print_result "SERVICE_STATUS" "$(systemctl is-active sing-box.service 2>/dev/null || true)"
  print_result "SERVICE_ENABLED" "$(systemctl is-enabled sing-box.service 2>/dev/null || true)"
  print_result "LISTEN_PORT" "${port:-UNAVAILABLE}"
  print_result "METHOD" "${method:-UNAVAILABLE}"
  print_result "PASSWORD" "$(mask_secret "$password")"
  print_result "LANDING_EGRESS_IP" "${egress:-UNAVAILABLE}"
  print_result "NODE_FILE" "$NODE_FILE"
  print_result "CREDENTIALS_FILE" "$CREDENTIALS_FILE"
}

generate_node() {
  require_root
  require_command jq
  load_state
  load_existing_credentials
  [ -f "$CONFIG_FILE" ] || die "landing config is not installed"
  LISTEN_PORT="${LISTEN_PORT:-$(existing_config_value '.inbounds[]? | select(.type == "shadowsocks") | .listen_port')}"
  SS_METHOD="${SS_METHOD:-$(existing_config_value '.inbounds[]? | select(.type == "shadowsocks") | .method')}"
  SS_PASSWORD="${SS_PASSWORD:-${EXISTING_PASSWORD:-$(existing_config_value '.inbounds[]? | select(.type == "shadowsocks") | .password')}}"
  validate_port_value "$LISTEN_PORT" || die "invalid configured listen port"
  [ "$SS_METHOD" = "aes-128-gcm" ] || die "configured method is not aes-128-gcm"
  validate_password_value "$SS_PASSWORD" || die "configured password is not in the supported safe format"
  if [ -z "${NODE_ADDRESS:-}" ]; then
    NODE_ADDRESS="$(prompt_required "Transit public IP or domain")"
  fi
  validate_node_address "$NODE_ADDRESS" || die "invalid transit public IP or domain"
  NODE_PORT="$(prompt_with_default "Transit public port" "${NODE_PORT:-$LISTEN_PORT}")"
  validate_port_value "$NODE_PORT" || die "invalid transit public port"
  NODE_NAME="$(prompt_with_default "Node name" "${NODE_NAME:-Lagos-SS}")"
  NODE_NAME="$(safe_fragment "$NODE_NAME")"
  [ -n "$NODE_NAME" ] || die "node name is empty"
  build_node_outputs
  start_backup landing-node
  backup_file "$STATE_FILE"
  backup_file "$NODE_FILE"
  write_root_file "$(render_state)" "$STATE_FILE" 600
  write_root_file "$(render_node_file)" "$NODE_FILE" 600
  printf 'Generic SS node:\n%s\n\nSurge policy:\n%s\n' "$SS_URI" "$SURGE_LINE"
  print_result "NODE_FILE" "$NODE_FILE"
  print_result "BACKUP_PATH" "$BACKUP_PATH"
}

show_credentials() {
  require_root
  [ -f "$CREDENTIALS_FILE" ] || die "credentials file does not exist"
  require_private_file "$CREDENTIALS_FILE"
  cat "$CREDENTIALS_FILE"
}

remove_landing() {
  require_root
  confirm_exact "This removes only the managed sing-box service, config, credentials, and node files." "REMOVE LANDING" || die "operation cancelled"
  start_backup landing-remove
  backup_file "$CONFIG_FILE"
  backup_file "$STATE_FILE"
  backup_file "$CREDENTIALS_FILE"
  backup_file "$NODE_FILE"
  backup_file "$UNIT_FILE"
  systemctl disable --now sing-box.service >/dev/null 2>&1 || true
  rm -f "$CONFIG_FILE" "$STATE_FILE" "$CREDENTIALS_FILE" "$NODE_FILE" "$UNIT_FILE"
  systemctl daemon-reload
  print_result "REMOVED" "yes"
  print_result "SING_BOX_BINARY" "preserved"
  print_result "BACKUP_PATH" "$BACKUP_PATH"
}

show_help() {
  cat <<EOF
Usage: sudo $0 [install|status|generate-node|show-credentials|remove|help] [--yes] [--non-interactive]

This script configures a local sing-box Shadowsocks landing service. It never
calls AWS CLI, AWS API, or EC2 Metadata. It emits a generic ss:// node and a
Surge policy when a transit public IP or domain is provided.
EOF
}

case "$ACTION" in
  install) require_landing_commands; install_landing ;;
  status) status_landing ;;
  generate-node) generate_node ;;
  show-credentials) show_credentials ;;
  remove) remove_landing ;;
  help) show_help ;;
esac
