#!/usr/bin/env bash

set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_PREFIX="aws-route-transit"
# shellcheck source=route-local-common.sh
source "$SCRIPT_DIR/route-local-common.sh"

STATE_FILE="${STATE_FILE:-$STATE_ROOT/transit.env}"
NFT_FILE="${NFT_FILE:-$STATE_ROOT/transit.nft}"
APPLY_FILE="${APPLY_FILE:-/usr/local/sbin/aws-route-transit-apply}"
UNIT_FILE="${UNIT_FILE:-/etc/systemd/system/aws-route-transit.service}"
SYSCTL_FILE="${SYSCTL_FILE:-/etc/sysctl.d/99-aws-route-transit.conf}"
TABLE_NAME="aws_route"

ACTION="install"
for argument in "$@"; do
  case "$argument" in
    install|status|remove|help) ACTION="$argument" ;;
    -h|--help) ACTION=help ;;
    --yes|-y) AUTO_APPROVE=1 ;;
    --non-interactive) INTERACTIVE=0 ;;
    *) die "unknown option: $argument" ;;
  esac
done

LANDING_PRIVATE_IP="${LANDING_PRIVATE_IP:-}"
FORWARD_PORT="${FORWARD_PORT:-8388}"
TRANSIT_INTERFACE="${TRANSIT_INTERFACE:-}"
TRANSIT_PRIVATE_IP="${TRANSIT_PRIVATE_IP:-}"

load_state() {
  [ -f "$STATE_FILE" ] || return 0
  require_private_file "$STATE_FILE"
  # The file is generated by this script and contains only validated values.
  # shellcheck disable=SC1090
  . "$STATE_FILE"
}

require_transit_commands() {
  require_root
  require_command bash
  require_command ip
  require_command awk
  require_command grep
  require_command systemctl
}

check_existing_forward_firewall() {
  local nft_conflicts iptables_rules

  nft_conflicts=""
  if command -v nft >/dev/null 2>&1; then
    nft_conflicts="$(nft list ruleset 2>/dev/null | awk '
      /^table / {table=$0}
      /hook forward/ && table !~ /aws_route/ {print table ": " $0}
    ' || true)"
  fi

  iptables_rules=""
  if command -v iptables >/dev/null 2>&1; then
    iptables_rules="$(iptables -S FORWARD 2>/dev/null | grep -Ev '^-P FORWARD ACCEPT$' || true)"
  fi

  if [ -n "$nft_conflicts" ] || [ -n "$iptables_rules" ]; then
    warn "existing forwarding firewall rules were detected"
    print_result "FIREWALL_CONFLICT" "yes"
    printf '%s\n' "No changes were made. Resolve the existing FORWARD rules, then run this script again."
    if [ -n "$nft_conflicts" ]; then
      printf '%s\n' "nftables forward hooks:"
      printf '%s\n' "$nft_conflicts" | sed 's/^/  /'
    fi
    if [ -n "$iptables_rules" ]; then
      printf '%s\n' "iptables FORWARD rules:"
      printf '%s\n' "$iptables_rules" | sed 's/^/  /'
    fi
    return 1
  fi
}

resolve_inputs() {
  local detected_interface detected_private

  detect_primary_route || die "could not detect the primary IPv4 interface and private address"
  detected_interface="$PRIMARY_INTERFACE"
  detected_private="$PRIMARY_PRIVATE_IP"

  if [ -z "$LANDING_PRIVATE_IP" ]; then
    LANDING_PRIVATE_IP="$(prompt_required "Landing private IPv4")"
  else
    LANDING_PRIVATE_IP="$(prompt_with_default "Landing private IPv4" "$LANDING_PRIVATE_IP")"
  fi
  validate_ipv4_value "$LANDING_PRIVATE_IP" || die "invalid landing private IPv4: $LANDING_PRIVATE_IP"
  if ! is_private_ipv4 "$LANDING_PRIVATE_IP"; then
    warn "$LANDING_PRIVATE_IP is not an RFC1918 private address"
    confirm_action "Continue with this target?" no || die "operation cancelled"
  fi

  FORWARD_PORT="$(prompt_with_default "Forward port" "$FORWARD_PORT")"
  validate_port_value "$FORWARD_PORT" || die "invalid forward port: $FORWARD_PORT"
  [ "$FORWARD_PORT" -ne 22 ] || die "refusing to use SSH port 22 as the forwarding port"

  TRANSIT_INTERFACE="$(prompt_with_default "Transit network interface" "${TRANSIT_INTERFACE:-$detected_interface}")"
  validate_interface_name "$TRANSIT_INTERFACE" || die "invalid network interface: $TRANSIT_INTERFACE"
  ip link show "$TRANSIT_INTERFACE" >/dev/null 2>&1 || die "network interface does not exist: $TRANSIT_INTERFACE"

  TRANSIT_PRIVATE_IP="$(ip -4 -o addr show dev "$TRANSIT_INTERFACE" scope global | awk 'NR == 1 {split($4, a, "/"); print a[1]}')"
  validate_ipv4_value "$TRANSIT_PRIVATE_IP" || die "could not detect a private IPv4 address on $TRANSIT_INTERFACE"

  log "Detected transit private IPv4: $TRANSIT_PRIVATE_IP"
}

render_nft_config() {
  cat <<EOF
table ip $TABLE_NAME {
  chain prerouting {
    type nat hook prerouting priority dstnat; policy accept;
    fib daddr type local tcp dport $FORWARD_PORT dnat to $LANDING_PRIVATE_IP:$FORWARD_PORT
    fib daddr type local udp dport $FORWARD_PORT dnat to $LANDING_PRIVATE_IP:$FORWARD_PORT
  }

  chain postrouting {
    type nat hook postrouting priority srcnat; policy accept;
    oifname "$TRANSIT_INTERFACE" ip daddr $LANDING_PRIVATE_IP tcp dport $FORWARD_PORT masquerade
    oifname "$TRANSIT_INTERFACE" ip daddr $LANDING_PRIVATE_IP udp dport $FORWARD_PORT masquerade
  }

  chain forward {
    type filter hook forward priority filter; policy drop;
    ct state established,related accept
    iifname "$TRANSIT_INTERFACE" ip daddr $LANDING_PRIVATE_IP tcp dport $FORWARD_PORT accept
    iifname "$TRANSIT_INTERFACE" ip daddr $LANDING_PRIVATE_IP udp dport $FORWARD_PORT accept
  }
}
EOF
}

render_state() {
  cat <<EOF
LANDING_PRIVATE_IP=$LANDING_PRIVATE_IP
FORWARD_PORT=$FORWARD_PORT
TRANSIT_INTERFACE=$TRANSIT_INTERFACE
TRANSIT_PRIVATE_IP=$TRANSIT_PRIVATE_IP
EOF
}

render_apply_script() {
  cat <<EOF
#!/bin/sh
set -eu
/usr/sbin/nft delete table ip $TABLE_NAME 2>/dev/null || true
/usr/sbin/nft -f $NFT_FILE
EOF
}

render_unit() {
  cat <<EOF
[Unit]
Description=AWS route transit forwarding
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=$APPLY_FILE
ExecReload=$APPLY_FILE
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF
}

render_sysctl() {
  printf 'net.ipv4.ip_forward=1\n'
}

TRANSIT_MUTATION_STARTED=0
TRANSIT_WAS_ACTIVE=0
TRANSIT_WAS_ENABLED=0
rollback_transit() {
  set +e
  systemctl disable --now aws-route-transit.service >/dev/null 2>&1 || true
  nft delete table ip "$TABLE_NAME" >/dev/null 2>&1 || true
  restore_file "$STATE_FILE"
  restore_file "$NFT_FILE"
  restore_file "$APPLY_FILE"
  restore_file "$UNIT_FILE"
  restore_file "$SYSCTL_FILE"
  systemctl daemon-reload >/dev/null 2>&1 || true
  if [ "$TRANSIT_WAS_ENABLED" -eq 1 ]; then
    systemctl enable aws-route-transit.service >/dev/null 2>&1 || true
  fi
  if [ "$TRANSIT_WAS_ACTIVE" -eq 1 ]; then
    systemctl start aws-route-transit.service >/dev/null 2>&1 || true
  fi
  set -e
}

on_transit_error() {
  local rc="$?"
  if [ "$TRANSIT_MUTATION_STARTED" -eq 1 ]; then
    warn "deployment failed; restoring the previous managed files"
    rollback_transit
  fi
  exit "$rc"
}

verify_transit() {
  local public_ip tcp_status

  systemctl is-active --quiet aws-route-transit.service || die "transit service is not active"
  systemctl is-enabled --quiet aws-route-transit.service || die "transit service is not enabled"
  [ "$(cat /proc/sys/net/ipv4/ip_forward)" = "1" ] || die "ip forwarding is not enabled"
  nft list table ip "$TABLE_NAME" >/dev/null 2>&1 || die "managed nftables table is not loaded"

  tcp_status="UNKNOWN"
  if command -v timeout >/dev/null 2>&1; then
    if timeout 5 bash -c "</dev/tcp/$LANDING_PRIVATE_IP/$FORWARD_PORT" >/dev/null 2>&1; then
      tcp_status="PASS"
    else
      tcp_status="FAIL"
      warn "landing TCP port is not reachable yet; forwarding rules are still installed"
    fi
  fi

  public_ip="$(get_public_ipv4 2>/dev/null || true)"
  printf '\nTransit forwarding is configured\n'
  print_result "DEPLOYMENT_STATUS" "READY"
  print_result "ROLE" "TRANSIT"
  print_result "PUBLIC_IP" "${public_ip:-UNAVAILABLE}"
  print_result "PRIVATE_IP" "$TRANSIT_PRIVATE_IP"
  print_result "INTERFACE" "$TRANSIT_INTERFACE"
  print_result "LISTEN_PORT" "$FORWARD_PORT"
  print_result "LANDING_TARGET" "$LANDING_PRIVATE_IP:$FORWARD_PORT"
  print_result "IP_FORWARD" "1"
  print_result "NFTABLES_STATUS" "active"
  print_result "TCP_TO_LANDING" "$tcp_status"
  print_result "UDP_RULE_STATUS" "PASS"
  print_result "SOURCE_DEST_CHECK" "UNVERIFIED"
  print_result "SECURITY_GROUP_STATUS" "UNVERIFIED"
  print_result "BACKUP_PATH" "$BACKUP_PATH"
}

install_transit() {
  local temporary_nft

  load_state
  resolve_inputs
  check_existing_forward_firewall || exit 2

  printf '\nDeployment plan:\n'
  detail "Role: transit EC2"
  detail "Interface: $TRANSIT_INTERFACE ($TRANSIT_PRIVATE_IP)"
  detail "Forward: TCP/UDP $FORWARD_PORT -> $LANDING_PRIVATE_IP:$FORWARD_PORT"
  detail "AWS API/CLI/Metadata: not used"
  confirm_action "Apply this plan?" no || die "operation cancelled"

  require_supported_debian
  start_backup transit
  backup_file "$STATE_FILE"
  backup_file "$NFT_FILE"
  backup_file "$APPLY_FILE"
  backup_file "$UNIT_FILE"
  backup_file "$SYSCTL_FILE"
  if systemctl is-active --quiet aws-route-transit.service; then
    TRANSIT_WAS_ACTIVE=1
  fi
  if systemctl is-enabled --quiet aws-route-transit.service; then
    TRANSIT_WAS_ENABLED=1
  fi
  TRANSIT_MUTATION_STARTED=1
  trap on_transit_error ERR

  export DEBIAN_FRONTEND=noninteractive
  apt-get update -qq
  apt-get install -y -qq nftables procps iproute2 >/dev/null

  temporary_nft="$(mktemp)"
  render_nft_config >"$temporary_nft"
  nft -c -f "$temporary_nft"
  unlink "$temporary_nft"

  write_root_file "$(render_state)" "$STATE_FILE" 600
  write_root_file "$(render_nft_config)" "$NFT_FILE" 644
  write_root_file "$(render_apply_script)" "$APPLY_FILE" 755
  write_root_file "$(render_unit)" "$UNIT_FILE" 644
  write_root_file "$(render_sysctl)" "$SYSCTL_FILE" 644

  sysctl -p "$SYSCTL_FILE" >/dev/null
  systemctl daemon-reload
  systemctl enable --now aws-route-transit.service >/dev/null
  verify_transit
  trap - ERR
}

status_transit() {
  local public_ip
  require_root
  require_command ip
  require_command systemctl
  load_state
  if [ -z "${LANDING_PRIVATE_IP:-}" ]; then
    print_result "DEPLOYMENT_STATUS" "NOT_CONFIGURED"
    return 0
  fi
  public_ip="$(get_public_ipv4 2>/dev/null || true)"
  print_result "ROLE" "TRANSIT"
  print_result "PUBLIC_IP" "${public_ip:-UNAVAILABLE}"
  print_result "PRIVATE_IP" "${TRANSIT_PRIVATE_IP:-UNAVAILABLE}"
  print_result "INTERFACE" "${TRANSIT_INTERFACE:-UNAVAILABLE}"
  print_result "LISTEN_PORT" "${FORWARD_PORT:-UNAVAILABLE}"
  print_result "LANDING_TARGET" "$LANDING_PRIVATE_IP:${FORWARD_PORT:-8388}"
  print_result "SERVICE_STATUS" "$(systemctl is-active aws-route-transit.service 2>/dev/null || true)"
  print_result "SERVICE_ENABLED" "$(systemctl is-enabled aws-route-transit.service 2>/dev/null || true)"
  print_result "IP_FORWARD" "$(cat /proc/sys/net/ipv4/ip_forward 2>/dev/null || true)"
  if command -v nft >/dev/null 2>&1 && nft list table ip "$TABLE_NAME" >/dev/null 2>&1; then
    print_result "NFTABLES_STATUS" "active"
  else
    print_result "NFTABLES_STATUS" "inactive"
  fi
}

remove_transit() {
  require_root
  load_state
  confirm_exact "This removes only the AWS route transit service and its managed files." "REMOVE TRANSIT" || die "operation cancelled"
  start_backup transit-remove
  backup_file "$STATE_FILE"
  backup_file "$NFT_FILE"
  backup_file "$APPLY_FILE"
  backup_file "$UNIT_FILE"
  backup_file "$SYSCTL_FILE"
  systemctl disable --now aws-route-transit.service >/dev/null 2>&1 || true
  if command -v nft >/dev/null 2>&1; then
    nft delete table ip "$TABLE_NAME" >/dev/null 2>&1 || true
  fi
  rm -f "$STATE_FILE" "$NFT_FILE" "$APPLY_FILE" "$UNIT_FILE" "$SYSCTL_FILE"
  systemctl daemon-reload
  warn "runtime ip_forward was left unchanged; only its persistence file was removed"
  print_result "REMOVED" "yes"
  print_result "BACKUP_PATH" "$BACKUP_PATH"
}

show_help() {
  cat <<EOF
Usage: sudo $0 [install|status|remove|help] [--yes] [--non-interactive]

This script configures only host-local forwarding. It never calls AWS CLI,
AWS API, or EC2 Metadata. It does not change security groups or source/dest
check. Existing FORWARD firewall rules cause install to stop without changes.
EOF
}

case "$ACTION" in
  install) require_transit_commands; install_transit ;;
  status) status_transit ;;
  remove) remove_transit ;;
  help) show_help ;;
esac
